name: TransferWDPE
version: 1.0.0
main: vazzi.TransferWDPE
author: 原作者Vazzi,由从不咕咕的鸽纸进行二创及汉化
api: ["1.0.0"]
permissions:
  wtransfer.command:
    description: "允许将玩家传送至WaterdogePE的下游服务器"
    default: true
